// This file was generated by go-dao-code-gen

package {{ .Pkg }}

import (
	"context"
	"errors"
	"reflect"
	"strings"
    "database/sql"

	"github.com/go-sql-driver/mysql"
)

const (
    // ShadowCtxKey specifies the shadow identity in context.
	ShadowCtxKey string = "X-Shadow"
    // ForceMasterIdentity specifies the force master tag in SQL comment.
    ForceMasterIdentity string = "/*force_master*/ "
)

var (
	globalDB     *sql.DB
)

// Init initializes the database connection and adds shadow mapping.
func Init(ctx context.Context, cfg *mysql.Config) (err error) {
    if cfg == nil {
        err = errors.New("mysql config is nil")
        return
    }
    connector, err := mysql.NewConnector(cfg)
    if err != nil {
        return
    }
	globalDB = sql.OpenDB(connector)
	return
}

// Close closes the connection pool. Use this in the main function via defer.
func Close() {
    if globalDB != nil {
        globalDB.Close()
    }
}

// InitTableFields initializes the field names list from a table entity.  
func InitTableFields(v any, fields *[]string) {
	t := reflect.TypeOf(v)
	*fields = make([]string, 0, t.NumField())
	var fieldName string
	for i := 0; i < t.NumField(); i++ {
		tag := t.Field(i).Tag.Get("db")
		fieldName = strings.Split(tag, ",")[0]
		if fieldName == "" {
			continue
		}
		*fields = append(*fields, strings.TrimSpace(fieldName))
	}
}

// InitTableAlias initializes the alias of fields from a table entity.
func InitTableAlias(v any, alias any) {
	rt := reflect.TypeOf(v)
	rv := reflect.ValueOf(alias)
	for i := 0; i < rt.NumField(); i++ {
		DBTag := rt.Field(i).Tag.Get("db")
		tags := strings.Split(DBTag, ",")
		if len(tags) < 1 {
			continue
		}
		rv.Elem().FieldByName(rt.Field(i).Name).SetString(tags[0])
	}
}

// GetOffset calculates the pagination offset.
func GetOffset(pageIndex int, pageLimit int) (offset int) {
    if pageLimit < 1 {
        pageLimit = 10
    }
    if pageIndex < 1 {
        pageIndex = 1
    }
    return (pageIndex - 1) * pageLimit
}
